### ISSUE TITLE
Data filtering by dataset

### ISSUE THREAD

**Issue by urtson** [geocollections/eurocore-db-ui#30] opened 2018-04-12 07:21 UTC
Analysis_summary table can now be filtered by dataset_id. As dataset ids are stored as array of integers, query filter must use contains lookuptype: 'dataset_id__contains=1,2'

**Comment by urtson** [comment] 2018-04-12 09:10
Update: use of lookuptype is not needed anymore, in any case it will be an OR search

**Comment by enmust** [comment] 2018-04-12 12:12
Added dataset search, but currently can't make it fully dependable because some requests don't work as expected.  

For example:

**1.** These two requests are used if user has entered dataset value and then using that value finds dependable analysis methods. I provided two examples. 
https://api.eurocore.rocks/drillcore/?analysis__dataset__id__in=1,2&distinct=true&fields=analysis__analysis_method__method,analysis__dataset__id
I shouldn't get values where analysis__dataset__id = null

https://api.eurocore.rocks/drillcore/?analysis__dataset__id=1&distinct=true&fields=analysis__analysis_method__method,analysis__dataset__id
I shouldn't get values where analysis__dataset__id = null and = 2

**2.** Also parameters are only dependable using the parameter__parameter fields because if I add unit__unit field then requests take too long (10 seconds and more)
https://api.eurocore.rocks/drillcore/?analysis__analysisresult__parameter__parameter=Ag&distinct=true&fields=analysis__analysis_method__method

https://api.eurocore.rocks/drillcore/?analysis__analysisresult__parameter__parameter=Ag&analysis__analysisresult__unit__unit=ppm&distinct=true&fields=analysis__analysis_method__method

**Comment by enmust** [comment] 2018-04-14 07:52
1. analysis__dataset__id was just for showing the results. 

2. I'll change the form order and put dataset right after drillcore. 

3. I thought the data search had to be dependable in every way like if user chooses **Ag ppm** it should show only those drillcores, methods and datasets which contain that parameter and unit. The problem is that currently I can only use the parameter part because if I added unit__unit to my requests some would take too long. Also right now my dependable search is using drillcore table to filter the values in multiselect boxes.
I don't know maybe there is a better query to make dependable search but if I use drillcore table then I can get all values into the same query without changing tables and field names.

**Comment by enmust** [comment] 2018-04-17 06:39
Closing this because now it is dependable using analysis table.

**Closed by enmust** 2018-04-17 06:39 UTC
Labels: enhancement
